name: jibli_admin_food
description: "A new Flutter project for Jibli Admin."
publish_to: 'none'

version: 1.0.1+66

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- State Management (Compatible Versions) ---
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^1.0.0  # الإصدار المتوافق مع Bloc 9 و Dart 3
  get_it: ^7.6.7

  # --- Network & API ---
  dio: ^5.4.0
  retrofit: ^4.1.0

  # --- Firebase & Notifications ---
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.0.0
  fluttertoast: ^8.2.1

  # --- Navigation & UI Components ---
  go_router: ^14.0.1
  flashy_tab_bar2: ^0.0.6
  animated_notch_bottom_bar: ^1.0.1
  flutter_sizer: ^1.0.4
  dropdown_button2: ^2.3.9
  flutter_smart_dialog: ^4.9.3+2
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  bottom_sheet: ^4.0.0
  flutter_animate: ^4.2.0+1
  smooth_page_indicator: ^1.1.0
  multi_dropdown: ^2.1.4
  bottom_picker: ^2.6.0
  awesome_dialog: ^3.2.0

  # --- Utilities & Logic ---
  envied: ^0.5.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.4
  flutter_hooks: ^0.20.5
  string_validator: ^1.0.0
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.1.11
  pinput: ^4.0.0
  sms_autofill: ^2.3.0
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  timeago: ^3.5.0
  open_filex: ^4.3.2
  path_provider: ^2.1.0

  # --- Icons ---
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  iconly: ^1.0.1
  ionicons: ^0.2.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- Code Generation (Compatible with Bloc 9 & Analyzer) ---
  bloc_test: ^10.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  envied_generator: ^0.5.3
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_jibli.jpeg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#EE4266"
  image: assets/logo/logo_jibli.jpeg
  android_12:
    color: "#EE4266"
    image: assets/logo/logo_jibli.jpeg

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/logo/
    - assets/
    - ios/Runner/GoogleService-Info.plist
    - ios/Runner/alarm.caf